let item = [
    {
        Sayur: [
            {name: "Buncis", jenis: "Sayur", harga: "5000", stok: "15"},
            {name: "Wortel", jenis: "Sayur", harga: "12000", stok: "20"},
            {name: "Brokoli", jenis: "Sayur", harga: "14000", stok: "3"},
            {name: "Sawi", jenis: "Sayur", harga: "8000", stok: "20"},
            {name: "Bawang", jenis: "Sayur", harga: "20000", stok: "18"},
            {name: "Kangkung", jenis: "Sayur", harga: "4500", stok: "16"},
            {name: "Kentang", jenis: "Sayur", harga: "20000", stok: "8"},
            {name: "Kelor", jenis: "Sayur", harga: "19000", stok: "10"},
            {name: "Bayam", jenis: "Sayur", harga: "14000", stok: "13"},
            {name: "Jahe", jenis: "Sayur", harga: "12000", stok: "14"},
            {name: "Kunyit", jenis: "Sayur", harga: "15000", stok: "4"},
            {name: "Terong", jenis: "Sayur", harga: "18000", stok: "20"},
            {name: "Cabe", jenis: "Sayur", harga: "17000", stok: "19"},
            {name: "Timun", jenis: "Sayur", harga: "10000", stok: "12"},
            {name: "Kol", jenis: "Sayur", harga: "20000", stok: "10"},
            {name: "Daun Singkong", jenis: "Sayur", harga: "6000", stok: "14"},
        ],
    },
    {
        buah: [
            {name: "Pepaya", jenis: "buah", harga: "7500", stok: "14"},
            {name: "Naga", jenis: "buah", harga: "12500", stok: "15"},
            {name: "Jeruk", jenis: "buah", harga: "12000", stok: "10"},
            {name: "Apel", jenis: "buah", harga: "14000", stok: "13"},
            {name: "Strowberi", jenis: "buah", harga: "15000", stok: "20"},
            {name: "Anggur", jenis: "buah", harga: "16000", stok: "19"},
            {name: "Nanas", jenis: "buah", harga: "20000", stok: "8"},
            {name: "Mangga", jenis: "buah", harga: "13500", stok: "17"},
            {name: "Kurma", jenis: "buah", harga: "5000", stok: "20"},
            {name: "Rambutan", jenis: "buah", harga: "14000", stok: "18"},
            {name: "Jambu", jenis: "buah", harga: "15000", stok: "17"},
            {name: "Durian", jenis: "buah", harga: "15500", stok: "5"},
            {name: "Alpukat", jenis: "buah", harga: "2500", stok: "20"},
            {name: "Manggis", jenis: "buah", harga: "4000", stok: "19"},
            {name: "Kiwi", jenis: "buah", harga: "12000", stok: "10"},
            {name: "Kelengkeng", jenis: "buah", harga: "10000", stok: "20"},
        ],
    },
];